services:
  validador:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techgirls-validador
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    working_dir: /app
    command: python src/bot.py
    restart: unless-stopped
